language: ruby
cache: bundler

rvm:
  - 1.9.3

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

before_script: 'bundle install'
script: 'bundle exec cucumber'

branches:
  only:
    - master

notifications:
  email:
    - isakib@gmail.com
